**You can use Google but don't use ChatGPT and Gemini. You are here to learn. Follow the instructions given below and write the code in that cell only.**


In [2]:
# Question 1: Create three variables one containing an integer value,
# one containing floating point value and the last one contains string value.
# Accept the value of all three variables from the user.
# Print out the data types of the variables using a predifined function.
# What is the square of the first and second variables? Add 97 to them. Subtract 3 from them and then divide them by the original value before squaring.
# Append your name to the third variable and display the value.
# Write your code in this cell.

x= int(input("enter an integer: "))
y= float(input("enter an floating-point: "))
z= input("enter a string: ")
print("type of x is ",type(x)) 
print("type of y is ",type(y)) 
print("type of z is ",type(z)) 
x=(x+97-3)/x
y=(y+97-3)/y
a=x**2
b=y**2
z+= " Abdul"
print(a)
print(b)
print(z)


enter an integer:  17
enter an floating-point:  21.7
enter a string:  hsoaievha


type of x is  <class 'int'>
type of y is  <class 'float'>
type of z is  <class 'str'>
42.63321799307958
28.428061755399355
hsoaievhaAbdul


In [5]:
# Question 2: Define a function that accepts a value and prints out the multipication table from 1 to 20.
# Write your code in this cell.
def table(num):
    for i in range(1,21):
        product= num*i
        print(product)
num= float(input("Enter a value: "))
table(num)


Enter a value:  5.2


5.2
10.4
15.600000000000001
20.8
26.0
31.200000000000003
36.4
41.6
46.800000000000004
52.0
57.2
62.400000000000006
67.60000000000001
72.8
78.0
83.2
88.4
93.60000000000001
98.8
104.0


In [11]:
# Question 3: How many vowels are present in the new value of the third variable?
# Write your code in this cell.
count=0
for i in range(0,len(z)):
    if z[i]=="A" or z[i]=="a" or z[i]=="E"or z[i]=="e"or z[i]=="I"or z[i]=="i"or z[i]=="O"or z[i]=="o"or z[i]=="u"or z[i]=="U":
        count+=1
print(count)

7


In [17]:
# Question 4: Start
# Import the numpy library
!pip install numpy
import numpy as np

In [18]:
# Create a numpy array of size 10.
arr=np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [19]:
# Resize the array to make it a column vector. So the shape will be (10, 1).
# Print the shape of the array to verify your answer
col_arr = arr.reshape((10, 1))
print(col_arr)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]


In [27]:
# Create a numpy array of the above shape where all elements are 1
# Add this array to the above column vector
arr1= np.full((10),1)
col_arr1 = arr1.reshape((10,1))
arr0= col_arr+col_arr1
print(arr0)


[[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [24]:
# Print out the first 5 rows of the new column vector after addition
print(arr0[ :5])


[[2]
 [3]
 [4]
 [5]
 [6]]


In [37]:
# Create a new array of the same shape which have random values
arr2=np.random.random_sample(col_arr.shape)+np.random.randint(-100000,100000,size=(10,1))
print(arr2)


[[-75772.24058758]
 [-95700.46983295]
 [-46636.13027078]
 [ -9092.19520648]
 [ 20174.02698671]
 [  3839.76821602]
 [-57084.11981372]
 [-86031.57777063]
 [-46514.27325844]
 [ 18557.04325556]]


In [43]:
# Now perform hstack() and vstack() and print out the shape and write in
# one line what difference you observe
arr3=np.array([[1,2,3,4],[1,3,5,7]])
arr4=np.array([[1,4,9,16],[1,9,25,49]])
arr5=np.vstack((arr3,arr4))
arr6=np.hstack((arr3,arr4))     
print(arr5)
print(arr6)
#hstack() combines arrays by adding columns at end whereas vstack() combines by adding row at the end       




[[ 1  2  3  4]
 [ 1  3  5  7]
 [ 1  4  9 16]
 [ 1  9 25 49]]
[[ 1  2  3  4  1  4  9 16]
 [ 1  3  5  7  1  9 25 49]]


In [47]:
# Make a list conatining 7 numbers (of your choice)
# Convert this into numpy array
# Explore how to do element wise squaring using (**) operator
# Print out the result
favlist=[1,21,25,37,7,16,36]
arr7=np.array(favlist)
arr7=arr7**2
print(arr7)

[   1  441  625 1369   49  256 1296]


In [55]:
# Question 4: End
# Explore broadcasting from the internet and explain what you understood with the help of an example.
arr8=np.random.randint(-10,10,size=(2,2))
print(arr8)
arr9=np.random.randint(-10,10,size=(2,1))
print("\n")
print(arr9)
arr10=arr8+arr9
print("\n")
print(arr10)
#what it does is it makes a matrix of bigger one(here (2,2)) consisting of repeating smaller matrix(here(2,1)) i.e since for 2,1 to be 2,2 one more column
#is needed so it repeats 1st column into second and do operation as requested



[[ 0  4]
 [-6 -9]]


[[-4]
 [-2]]


[[ -4   0]
 [ -8 -11]]


**Dataset Link:** https://www.kaggle.com/datasets/himanshunakrani/iris-dataset

**If you are using Google Colab:<br>
Step 1: Upload the dataset on your drive<br>
Step 2: In the left most part of you screen there are 5 options at the top and 3 options at the bottm.<br>
Step 3: Click on Files option (last option in the top below the key symbol)<br>
Step 4: Click on mount drive and wait.<br>
Step 5: Now you can see a folder named drive.<br>
Step 6: Click on it. Click on MyDrive. Now you can see all your files here.<br>
Step 7: Use Ctrl+F to search the name of the dataset.<br>
Step 8: Right click on it and click on copy path**






**If you are using Jupyter Notebook:<br>
Step 1: Create a new folder.<br>
Step 2: Add the dataset in this folder<br>
Step 3: Copy this notebook to the same folder.<br>
Step 4: Now you can easily copy the path**

In [56]:
# Question 5: Start
# import pandas library
!pip install pandas
import pandas as pd


In [13]:
# Copy your path and store in the below variable.
# Note that the path will be a string

# Uncomment the below line
path = 'iris.csv'

#Load the dataframe


In [31]:
# Print out the first 7 rows using head()

df = pd.read_csv(path)
print(df.head(7))


   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa


In [32]:
# Print out the last 10 rows
print(df.tail(10))

     sepal_length  sepal_width  petal_length  petal_width    species
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica


In [33]:
# How many rows and columns are there in this dataset
r,c= df.shape
print(r)
print(c)

150
5


In [34]:
# Print the info of this dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [35]:
# Check if the dataset has null values
null_values= df.isnull().sum()
print(null_values)

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64


In [36]:
# From the describe method what is std (standard deviation) of petal_width
desc = df.describe()

# Print the standard deviation of the 'petal_width' column
std_pw = desc.loc['std', 'petal_width']
print(std_pw)

0.7631607417008414


In [37]:
# Print out all the names of the column using a predifined method
print(df.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


In [38]:
# How many types of values are there in species column
val = df['species'].unique()
print(val)

['setosa' 'versicolor' 'virginica']


In [39]:
# Select all rows whose species column value is setosa
# Print out the shape of this dataframe
val_setosa = df[df['species'] == 'setosa']
print(val_setosa.shape)

(50, 5)


In [40]:
# Select all rows whose species column value is virginica
# Print out the shape of this dataframe
val_virginica = df[df['species'] == 'virginica']
print(val_virginica.shape)

(50, 5)


In [43]:
# Make a new dataframe called "df_new" by concatenating the above dataframes
# Print out the shape of this dataframe
df_new = pd.concat([val_setosa, val_virginica])
print(df_new.shape)

(100, 5)


In [44]:
# Print the average sepal_length of these two species
avg_sl = df_new.groupby('species')['sepal_length'].mean()
print(avg_sl)

species
setosa       5.006
virginica    6.588
Name: sepal_length, dtype: float64


In [49]:
# Create a new column called "sepal_area" which is computed by taking the product of sepal_length and sepal_width
# Print the min and max area
df_new['sepal_area'] = df_new['sepal_length'] * df_new['sepal_width']
min_area = df_new['sepal_area'].min()
max_area = df_new['sepal_area'].max()
print(min_area)
print(max_area)


10.35
30.02


In [50]:
# Print out all the names of the columns using predefined method
print(df_new.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species',
       'sepal_area'],
      dtype='object')


In [51]:
# From the above output copy all the names except petal_length and store it in a list
colmns= list(df_new.columns)
colmns.remove('petal_length')
print(colmns)

['sepal_length', 'sepal_width', 'petal_width', 'species', 'sepal_area']


In [53]:
# From the above list create a new dataframe "df_new2" from df_new which have only the columns mentioned in the list
# Print out the shape
df_new2 = df_new.loc[:, colmns]
print(df_new2.shape)


(100, 5)


In [57]:
# Swap setosa with 1
# Swap virginica with 0
# Do this using replace()
df_new['species'] = df_new['species'].replace({'setosa': 1, 'virginica': 0})
print(df_new.head(150))

     sepal_length  sepal_width  petal_length  petal_width  species  sepal_area
0             5.1          3.5           1.4          0.2        1       17.85
1             4.9          3.0           1.4          0.2        1       14.70
2             4.7          3.2           1.3          0.2        1       15.04
3             4.6          3.1           1.5          0.2        1       14.26
4             5.0          3.6           1.4          0.2        1       18.00
..            ...          ...           ...          ...      ...         ...
145           6.7          3.0           5.2          2.3        0       20.10
146           6.3          2.5           5.0          1.9        0       15.75
147           6.5          3.0           5.2          2.0        0       19.50
148           6.2          3.4           5.4          2.3        0       21.08
149           5.9          3.0           5.1          1.8        0       17.70

[100 rows x 6 columns]


**Assignment END<br>
Please submit this on teams before the deadline**