**You can use Google but don't use ChatGPT and Gemini. You are here to learn. Follow the instructions given below and write the code in that cell only.**


In [ ]:
# Question 1: Create three variables one containing an integer value,
# one containing floating point value and the last one contains string value.
# Accept the value of all three variables from the user.
# Print out the data types of the variables using a predifined function.
# What is the square of the first and second variables? Add 97 to them. Subtract 3 from them and then divide them by the original value before squaring.
# Append your name to the third variable and display the value.
# Write your code in this cell.


a= int(input('Enter a integer:'))
b = float(input('Enter a float :'))
c = str(input('Enter a string :'))
print('Data type of a:',type(a))
print('Data type of b:',type(b))
print('Data type of c:',type(c))
print('\n')
print('square of a :',a**2)
print('square of b :',b**2)
print('\n')

x = a**2 + 97
y = b**2 + 97
print('value of x:',x)
print('value of y:',y)
z = x - 3
w = y - 3
print('value of z:',z)
print('value of w:',w)
p = z/a
q = w/b
print('value of p:',p)
print('value of q:',q)
final_variable = c + 'Amarjeet'
print(final_variable)



Enter a integer:2
Enter a float :3.5
Enter a string :Hello !
Data type of a: <class 'int'>
Data type of b: <class 'float'>
Data type of c: <class 'str'>


square of a : 4
square of b : 12.25


value of x: 101
value of y: 109.25
value of z: 98
value of w: 106.25
value of p: 49.0
value of q: 30.357142857142858
Hello !Amarjeet


In [ ]:
# Question 2: Define a function that accepts a value and prints out the multipication table from 1 to 20.
# Write your code in this cell.

def table(x):
  for i in range(1,21):
    print(f'{x}X{i} = {x*i}')
table(5)

5X1 = 5
5X2 = 10
5X3 = 15
5X4 = 20
5X5 = 25
5X6 = 30
5X7 = 35
5X8 = 40
5X9 = 45
5X10 = 50
5X11 = 55
5X12 = 60
5X13 = 65
5X14 = 70
5X15 = 75
5X16 = 80
5X17 = 85
5X18 = 90
5X19 = 95
5X20 = 100


In [ ]:
# Question 3: How many vowels are present in the new value of the third variable?
# Write your code in this cell.

vowels = 'AEIOUaeiou'
count = 0
for i in c:
  if i in vowels:
    count+=1
print('Number of vowels in c :',count)

Number of vowels in c : 2


In [ ]:
# Question 4: Start
# Import the numpy library
import numpy as np


In [ ]:
# Create a numpy array of size 10.
my_list = [i for i in range(10,20)]
x =np.array(my_list)
print(x.shape)

(10,)


In [ ]:
# Resize the array to make it a column vector. So the shape will be (10, 1).
# Print the shape of the array to verify your answer
x= x.reshape(10,1)
print(x.shape)

(10, 1)


In [ ]:
# Create a numpy array of the above shape where all elements are 1
# Add this array to the above column vector


arr_1 = np.ones(10).reshape(10,1)
sum = x + arr_1
sum

array([[11.],
       [12.],
       [13.],
       [14.],
       [15.],
       [16.],
       [17.],
       [18.],
       [19.],
       [20.]])

In [ ]:
# Print out the first 5 rows of the new column vector after addition
for i in range(5):
  print(sum[i][0])

11.0
12.0
13.0
14.0
15.0


In [ ]:
# Create a new array of the same shape which have random values

rand_arr = np.random.randint(1,20,(10,1))
rand_arr

array([[ 2],
       [ 7],
       [ 4],
       [ 4],
       [ 5],
       [ 5],
       [ 9],
       [ 7],
       [18],
       [ 2]])

In [ ]:
# Now perform hstack() and vstack() and print out the shape and write in
# one line what difference you observe

A = np.array([1,2,3,4])
B = np.array([5,6,7,8])

C=np.vstack((A,B))
print(C)
print(C.shape)
print('\n')
D = np.hstack((A,B))
print(D)
print(D.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


[1 2 3 4 5 6 7 8]
(8,)


**hstack add array horizontally & vstack add array vertically.**

In [ ]:
# Make a list conatining 7 numbers (of your choice)
# Convert this into numpy array
# Explore how to do element wise squaring using (**) operator
# Print out the result
list_2 = [1,3,7,8,9,12,15]
arr_2 = np.array(list_2)
sqr_arr = arr_2**2
sqr_arr

array([  1,   9,  49,  64,  81, 144, 225])

In [ ]:
# Question 4: End
# Explore broadcasting from the internet and explain what you understood with the help of an example.


# Broadcasting help us to perform operation on arrays of different shapes.
#The smaller array is broadcast to the size of the larger array so that they have compatible shape.

# Example
k = np.arange(6).reshape(2,3)
l = np.arange(3).reshape(1,3)

print(k)
print(k.shape)
print(l)
print(l.shape)
print()
k+l

[[0 1 2]
 [3 4 5]]
(2, 3)
[[0 1 2]]
(1, 3)



array([[0, 2, 4],
       [3, 5, 7]])

**Dataset Link:** https://www.kaggle.com/datasets/himanshunakrani/iris-dataset

**If you are using Google Colab:<br>
Step 1: Upload the dataset on your drive<br>
Step 2: In the left most part of you screen there are 5 options at the top and 3 options at the bottm.<br>
Step 3: Click on Files option (last option in the top below the key symbol)<br>
Step 4: Click on mount drive and wait.<br>
Step 5: Now you can see a folder named drive.<br>
Step 6: Click on it. Click on MyDrive. Now you can see all your files here.<br>
Step 7: Use Ctrl+F to search the name of the dataset.<br>
Step 8: Right click on it and click on copy path**






**If you are using Jupyter Notebook:<br>
Step 1: Create a new folder.<br>
Step 2: Add the dataset in this folder<br>
Step 3: Copy this notebook to the same folder.<br>
Step 4: Now you can easily copy the path**

In [ ]:
# Question 5: Start
# import pandas library
import pandas as pd

In [ ]:
# Copy your path and store in the below variable.
# Note that the path will be a string

# Uncomment the below line
"""
path = your path of the dataset
"""

# Load the dataframe
df = pd.read_csv('iris.csv')


In [ ]:
# Print out the first 7 rows using head()
df.head(7)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa

In [ ]:
# Print out the last 10 rows
df.tail(10)

sepal_length  sepal_width  petal_length  petal_width    species
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [ ]:
# How many rows and columns are there in this dataset
print(f'No.of rows in dataset :{df.shape[0]}')
print(f'No.of columns in dataset : {df.shape[1]}')

No.of rows in dataset :150
No.of columns in dataset : 5


In [ ]:
# Print the info of this dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
# Check if the dataset has null values
df.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
# From the describe method what is std (standard deviation) of petal_width
print(df.describe())
print('\n')
print('standard deviation of petal width :',0.763161)

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000


standard deviation of petal width : 0.763161


In [ ]:
# Print out all the names of the column using a predifined method
df.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
# How many types of values are there in species column
df['species'].unique()

array(['setosa', 'versicolor', 'virginica'], dtype=object)

In [ ]:
# Select all rows whose species column value is setosa
# Print out the shape of this dataframe
setosa = df[df['species']=='setosa']
setosa.shape

(50, 5)

In [ ]:
# Select all rows whose species column value is virginica
# Print out the shape of this dataframe
virginica = df[df['species']=='virginica']
virginica.shape

(50, 5)

In [ ]:
# Make a new dataframe called "df_new" by concatenating the above dataframes
# Print out the shape of this dataframe

df_new = pd.concat([setosa,virginica],ignore_index = True)
df_new.shape

(100, 5)

In [ ]:
# Print the average sepal_length of these two species
df_new.groupby('species')['sepal_length'].mean()

species
setosa       5.006
virginica    6.588
Name: sepal_length, dtype: float64

In [ ]:
# Create a new column called "sepal_area" which is computed by taking the product of sepal_length and sepal_width
# Print the min and max area

df_new['sepal_area'] = df['sepal_length']*df['sepal_width']
print('Minimum sepal area :',df_new['sepal_area'].min())
print('Maximum sepal area :',df_new['sepal_area'].max())

Minimum sepal area : 10.0
Maximum sepal area : 25.080000000000002


In [ ]:
# Print out all the names of the columns using predefined method
df_new.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species',
       'sepal_area'],
      dtype='object')

In [ ]:
# From the above output copy all the names except petal_length and store it in a list
column_list = ['sepal_length', 'sepal_width', 'petal_width', 'species','sepal_area']

In [ ]:
# From the above list create a new dataframe "df_new2" from df_new which have only the columns mentioned in the list
# Print out the shape
df_new2 = df_new[column_list]
df_new2.shape

(100, 5)

In [ ]:
# Swap setosa with 1
# Swap virginica with 0
# Do this using replace()

df_new2['species'] = df_new2['species'].replace({'setosa':1,'virginica':0})
df_new2

<ipython-input-52-21f79aa70ec2>:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new2['species'] = df_new2['species'].replace({'setosa':1,'virginica':0})


sepal_length  sepal_width  petal_width  species  sepal_area
0            5.1          3.5          0.2        1       17.85
1            4.9          3.0          0.2        1       14.70
2            4.7          3.2          0.2        1       15.04
3            4.6          3.1          0.2        1       14.26
4            5.0          3.6          0.2        1       18.00
..           ...          ...          ...      ...         ...
95           6.7          3.0          2.3        0       17.10
96           6.3          2.5          1.9        0       16.53
97           6.5          3.0          2.0        0       17.98
98           6.2          3.4          2.3        0       12.75
99           5.9          3.0          1.8        0       15.96

[100 rows x 5 columns]

**Assignment END<br>
Please submit this on teams before the deadline**