**You can use Google but don't use ChatGPT and Gemini. You are here to learn. Follow the instructions given below and write the code in that cell only.**


In [40]:
# Question 1: Create three variables one containing an integer value,
# one containing floating point value and the last one contains string value.
# Accept the value of all three variables from the user.
# Print out the data types of the variables using a predifined function.
# What is the square of the first and second variables? Add 97 to them. Subtract 3 from them and then divide them by the original value before squaring.
# Append your name to the third variable and display the value.
# Write your code in this cell.

a = int(input())
b = float(input())
c = input()
print(type(a),type(b),type(c))
update_a = ((a + 97 - 3)/a)**2
update_b = ((b + 97 - 3)/b)**2
print( update_a)
print( update_b)
c=c+"Hasaan"
print(c)






1
2.4
MYNAMEis
<class 'int'> <class 'float'> <class 'str'>
9025.0
1613.3611111111115
MYNAMEisHasaan


In [19]:
# Question 2: Define a function that accepts a value and prints out the multipication table from 1 to 20.
# Write your code in this cell.

def multipication_table(n):
    for i in range(1,21):
        print(n,"*",i,"=",n*i)
n = int(input())
multipication_table(n)

2
2 * 1 = 2
2 * 2 = 4
2 * 3 = 6
2 * 4 = 8
2 * 5 = 10
2 * 6 = 12
2 * 7 = 14
2 * 8 = 16
2 * 9 = 18
2 * 10 = 20
2 * 11 = 22
2 * 12 = 24
2 * 13 = 26
2 * 14 = 28
2 * 15 = 30
2 * 16 = 32
2 * 17 = 34
2 * 18 = 36
2 * 19 = 38
2 * 20 = 40


In [43]:
# Question 3: How many vowels are present in the new value of the third variable?
# Write your code in this cell.
def count_Vowels(value):
    count = 0
    for i in value: 
        if(i=='a' or i=='e' or i=='i'or i=='o' or i=='u' or i=='A' or i=='E' or i=='I' or i=='O' or i=='U'):
            count = count+1
            
            
    return count  
    
print(count_Vowels(c))


6


In [29]:
# Question 4: Start
# Import the numpy library
import numpy as np


In [30]:
# Create a numpy array of size 10.
a = np.array([1,2,3,4,5,6,7,8,9,10])


In [31]:
# Resize the array to make it a column vector. So the shape will be (10, 1).
# Print the shape of the array to verify your answer
a = a.reshape(10,1)
print(a.shape)



(10, 1)


In [32]:
# Create a numpy array of the above shape where all elements are 1
# Add this array to the above column vector

b = np.full((10,1),1)
sum = a+b



In [33]:
# Print out the first 5 rows of the new column vector after addition
for i in range (0,5):
    print(sum[i,])


[2]
[3]
[4]
[5]
[6]


In [34]:
# Create a new array of the same shape which have random values

d = np.random.randint(-10,100, size=(10,1))


In [45]:
# Now perform hstack() and vstack() and print out the shape and write in
# one line what difference you observe

v1 = np.array([1,2,3,4,5])
v2 = np.array([10,20,30,40,50])
v3 =np.vstack([v1,v2]) #vstack()
print(v3)



h1 = np.full((2,2),-5)
h2 = np.full((2,1),99)
h3 = np.hstack((v3,h1,h2))  #hstack()
print(h3)


# vstack() is like adding rows to a matrix, whereas hstack() is like adding coloums to a matrix.

[[ 1  2  3  4  5]
 [10 20 30 40 50]]
[[ 1  2  3  4  5 -5 -5 99]
 [10 20 30 40 50 -5 -5 99]]


In [37]:
# Make a list conatining 7 numbers (of your choice)
# Convert this into numpy array
# Explore how to do element wise squaring using (**) operator
# Print out the result

l = [10,20,30,40,50,60,70]
m = np.array(l) 
print(m**2)

[ 100  400  900 1600 2500 3600 4900]


In [93]:
# Question 4: End
# Explore broadcasting from the internet and explain what you understood with the help of an example.





**Dataset Link:** https://www.kaggle.com/datasets/himanshunakrani/iris-dataset

**If you are using Google Colab:<br>
Step 1: Upload the dataset on your drive<br>
Step 2: In the left most part of you screen there are 5 options at the top and 3 options at the bottm.<br>
Step 3: Click on Files option (last option in the top below the key symbol)<br>
Step 4: Click on mount drive and wait.<br>
Step 5: Now you can see a folder named drive.<br>
Step 6: Click on it. Click on MyDrive. Now you can see all your files here.<br>
Step 7: Use Ctrl+F to search the name of the dataset.<br>
Step 8: Right click on it and click on copy path**






**If you are using Jupyter Notebook:<br>
Step 1: Create a new folder.<br>
Step 2: Add the dataset in this folder<br>
Step 3: Copy this notebook to the same folder.<br>
Step 4: Now you can easily copy the path**

In [116]:
# Question 5: Start
# import pandas library
import pandas as pd


In [133]:
# Copy your path and store in the below variable.
# Note that the path will be a string

# Uncomment the below line

path = pd.read_csv('iris.csv')


# Load the dataframe


In [118]:
# Print out the first 7 rows using head()
print(path.head(7))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa


In [99]:
# Print out the last 10 rows
print(path.tail(10))

     sepal_length  sepal_width  petal_length  petal_width    species
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica


In [100]:
# How many rows and columns are there in this dataset
print(path.shape)

(150, 5)


In [101]:
# Print the info of this dataset
print(path.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None


In [167]:
# Check if the dataset has null values
path.isnull()
   

sepal_length  sepal_width  petal_length  petal_width  species
0           False        False         False        False    False
1           False        False         False        False    False
2           False        False         False        False    False
3           False        False         False        False    False
4           False        False         False        False    False
..            ...          ...           ...          ...      ...
145         False        False         False        False    False
146         False        False         False        False    False
147         False        False         False        False    False
148         False        False         False        False    False
149         False        False         False        False    False

[150 rows x 5 columns]

In [103]:
# From the describe method what is std (standard deviation) of petal_width
print("The standard deviation of petals_width =",path['petal_width'].describe()['std'])

The standard deviation of petals_width = 0.7631607417008414


In [104]:
# Print out all the names of the column using a predifined method
for i in path.columns:
    print(i)

sepal_length
sepal_width
petal_length
petal_width
species


In [105]:
# How many types of values are there in species column
print("There are",path['species'].describe()['unique'],"types of values in species column.")

There are 3 types of values in species column.


In [106]:
# Select all rows whose species column value is setosa
# Print out the shape of this dataframe
p1 = path[path['species']== "setosa"]
print(p1.shape)

(50, 5)


In [107]:
# Select all rows whose species column value is virginica
# Print out the shape of this dataframe
p2 = path[path['species']== "virginica"]
print(p2.shape)


(50, 5)


In [149]:
# Make a new dataframe called "df_new" by concatenating the above dataframes
# Print out the shape of this dataframe

df_new = pd.concat([p1,p2])
print(df_new.shape)

(100, 5)


In [128]:
# Print the average sepal_length of these two species
print(df_new['sepal_length'].describe()['mean'])


5.797


In [150]:
# Create a new column called "sepal_area" which is computed by taking the product of sepal_length and sepal_width
# Print the min and max area

df_new.insert(4,"sepal_area",path.sepal_length*path.sepal_width) 
print("Minimum Area= ",df_new['sepal_area'].describe()['min'])
print("Maximum Area= ",df_new['sepal_area'].describe()['max'])

Minimum Area=  10.35
Maximum Area=  30.02


In [151]:
# Print out all the names of the columns using predefined method
for i in df_new.columns:
    print(i)

sepal_length
sepal_width
petal_length
petal_width
sepal_area
species


In [152]:
# From the above output copy all the names except petal_length and store it in a list
l=[]
for i in df_new.columns:
    if i!="petal_length":
        l.append(i)
print(l)

['sepal_length', 'sepal_width', 'petal_width', 'sepal_area', 'species']


In [153]:
# From the above list create a new dataframe "df_new2" from df_new which have only the columns mentioned in the list
# Print out the shape
df_new2 = df_new[l]
print(df_new2.shape)


(100, 5)


In [164]:
# Swap setosa with 1
# Swap virginica with 0
# Do this using replace()
df_new2=df_new2.replace("setosa",1)
df_new2=df_new2.replace("virginica",0)
print(df_new2)

     sepal_length  sepal_width  petal_width  sepal_area  species
0             5.1          3.5          0.2       17.85        1
1             4.9          3.0          0.2       14.70        1
2             4.7          3.2          0.2       15.04        1
3             4.6          3.1          0.2       14.26        1
4             5.0          3.6          0.2       18.00        1
..            ...          ...          ...         ...      ...
145           6.7          3.0          2.3       20.10        0
146           6.3          2.5          1.9       15.75        0
147           6.5          3.0          2.0       19.50        0
148           6.2          3.4          2.3       21.08        0
149           5.9          3.0          1.8       17.70        0

[100 rows x 5 columns]


**Assignment END<br>
Please submit this on teams before the deadline**