**You can use Google but don't use ChatGPT and Gemini. You are here to learn. Follow the instructions given below and write the code in that cell only.**


In [1]:
# Question 1: Create three variables one containing an integer value,
# one containing floating point value and the last one contains string value.
# Accept the value of all three variables from the user.
# Print out the data types of the variables using a predifined function.
# What is the square of the first and second variables? Add 97 to them. Subtract 3 from them and then divide them by the original value before squaring.
# Append your name to the third variable and display the value.
# Write your code in this cell.
# Accept values from the user
var1 = int(input("Enter an integer value: "))
var2 = float(input("Enter a float value: "))
var3 = input("Enter a string: ")
print(type(var1))
print(type(var2))
print(type(var3))
# square of first and second variables.
print(var1**2, var2**2)
# values after the given task
print((var1**2 + 97 - 3)/ var1)
print((var2**2 + 97 - 3)/ var2)

a = var3 + "anish"
print(a)

<class 'int'>
<class 'float'>
<class 'str'>
400 5.4289000000000005
24.7
42.67334763948498
demonanish


In [2]:
# Question 2: Define a function that accepts a value and prints out the multipication table from 1 to 20.
# Write your code in this cell.
def table(value):
    for i in range(1,21):
        print(value*i)


data = 5
table(data)



5
10
15
20
25
30
35
40
45
50
55
60
65
70
75
80
85
90
95
100


In [3]:
# Question 3: How many vowels are present in the new value of the third variable?
# Write your code in this cell.

vowels = "aeiouAEIOU"       # saved the vowels in a string , we'll find them in the third variable string.
cnt = 0
for i in a:
    if i in vowels:
        cnt += 1
print("Number of vowels in", a ,"is:", cnt)



Number of vowels in demonanish is: 4


In [5]:
# Question 4: Start
# Import the numpy library

%pip install numpy
import numpy as np


Note: you may need to restart the kernel to use updated packages.


In [6]:
# Create a numpy array of size 10.
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
# Resize the array to make it a column vector. So the shape will be (10, 1).
# Print the shape of the array to verify your answer

col_arr = arr.reshape(10,1)       
print(col_arr)
print(col_arr.shape)



[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]]
(10, 1)


In [8]:
# Create a numpy array of the above shape where all elements are 1
# Add this array to the above column vector

allone = np.ones((10,1), dtype='int64')
newarr = col_arr + allone
print(newarr)


[[ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [9]:
# Print out the first 5 rows of the new column vector after addition
print(newarr[ : 5 ])


[[2]
 [3]
 [4]
 [5]
 [6]]


In [10]:
# Create a new array of the same shape which have random values

arr1 = np.random.randint(-1000,1000,(10,1))     # random int values from -1000 to 1000 
print(arr1)

[[-169]
 [ 772]
 [-869]
 [  81]
 [  62]
 [ 610]
 [-622]
 [-853]
 [   6]
 [ 861]]


In [11]:
# Now perform hstack() and vstack() and print out the shape and write in
# one line what difference you observe


a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])

a3 = np.hstack((a1,a2))     # Horizontally stacks/merges the arrays.
print(a3)
a4 = np.vstack((a1,a2))     # Vertically stacks/merges the arrays.
print(a4)



[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [12]:
# Make a list conatining 7 numbers (of your choice)
# Convert this into numpy array
# Explore how to do element wise squaring using (**) operator
# Print out the result

lst = [1,2,3,4,5,6,7]
a5 = np.array(lst)
a5 = a5**2
print(a5)


[ 1  4  9 16 25 36 49]


In [13]:
# Question 4: End
# Explore broadcasting from the internet and explain what you understood with the help of an example.

'''
Broadcasting defines how numpy deals with arrays during its arithmatic operations having different shapes.
The smaller is broadcast across the larger array so that they have compatible shape to perform the arithematic
operations given to it.

'''
# for example:-

b = np.array([1,2,3,4])         # b is a (1,4) matrix
c = np.array([4,9,16])
c = c.reshape((3,1))            # c is a (3,1) matrix

print(b)
print(c)
print('\n')
# if we add both arrays we'll get an (3,4) array
d = b + c
# b will broadcast itself into a (3,4) matrix having all rows identical and equal to [1,2,3,4].
# c will broadcast itself intoi a (3,4) matrix having all columns idencal and equal to [4,9,16] in a column form.
print(d)

# but this will not change the original arrays.
print('\n')
print(b)
print(c)


[1 2 3 4]
[[ 4]
 [ 9]
 [16]]


[[ 5  6  7  8]
 [10 11 12 13]
 [17 18 19 20]]


[1 2 3 4]
[[ 4]
 [ 9]
 [16]]


**Dataset Link:** https://www.kaggle.com/datasets/himanshunakrani/iris-dataset

**If you are using Google Colab:<br>
Step 1: Upload the dataset on your drive<br>
Step 2: In the left most part of you screen there are 5 options at the top and 3 options at the bottm.<br>
Step 3: Click on Files option (last option in the top below the key symbol)<br>
Step 4: Click on mount drive and wait.<br>
Step 5: Now you can see a folder named drive.<br>
Step 6: Click on it. Click on MyDrive. Now you can see all your files here.<br>
Step 7: Use Ctrl+F to search the name of the dataset.<br>
Step 8: Right click on it and click on copy path**






**If you are using Jupyter Notebook:<br>
Step 1: Create a new folder.<br>
Step 2: Add the dataset in this folder<br>
Step 3: Copy this notebook to the same folder.<br>
Step 4: Now you can easily copy the path**

In [15]:
# Question 5: Start
# import pandas library

%pip install pandas
import pandas as pd

Note: you may need to restart the kernel to use updated packages.


In [16]:
# Copy your path and store in the below variable.
# Note that the path will be a string

# Uncomment the below line
"""
path = your path of the dataset
"""

# Load the dataframe

file = pd.read_csv('iris.csv')
print(file)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]


In [17]:
# Print out the first 7 rows using head()
print(file.head(7))


   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa


In [18]:
# Print out the last 10 rows
print(file.tail(10))

     sepal_length  sepal_width  petal_length  petal_width    species
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica


In [19]:
# How many rows and columns are there in this dataset
print("Number of rows in file is:",file.shape[0])
print("Number of columns in file is:",file.shape[1])

Number of rows in file is: 150
Number of columns in file is: 5


In [20]:
# Print the info of this dataset
file.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [21]:
# Check if the dataset has null values

null_values = file.isnull().sum()
print(null_values)


sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64


In [22]:
# From the describe method what is std (standard deviation) of petal_width

summary = file.describe()
st_dev = summary.loc['std','petal_width']
print(st_dev)


0.7631607417008411


In [23]:
# Print out all the names of the column using a predifined method
print(file.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')


In [24]:
# How many types of values are there in species column
type = file['species'].unique()
print(type)


['setosa' 'versicolor' 'virginica']


In [25]:
# Select all rows whose species column value is setosa
# Print out the shape of this dataframe

setosa = file[file['species'] == "setosa"]
print(setosa.shape)

(50, 5)


In [26]:
# Select all rows whose species column value is virginica
# Print out the shape of this dataframe

virginica = file[file['species'] == "virginica"]
print(virginica.shape)

(50, 5)


In [27]:
# Make a new dataframe called "df_new" by concatenating the above dataframes
# Print out the shape of this dataframe

df_new = pd.concat([setosa,virginica], ignore_index = True)
print(df_new.shape)


(100, 5)


In [28]:
# Print the average sepal_length of these two species
df_new.groupby('species')['sepal_length'].mean()

species
setosa       5.006
virginica    6.588
Name: sepal_length, dtype: float64

In [29]:
# Create a new column called "sepal_area" which is computed by taking the product of sepal_length and sepal_width
# Print the min and max area

df_new['sepal_area'] = file['sepal_length']*file['sepal_width']
print('Minimum sepal area is:',df_new['sepal_area'].min())
print('Maximum sepal area is:',df_new['sepal_area'].max())

Minimum sepal area is: 10.0
Maximum sepal area is: 25.080000000000002


In [30]:
# Print out all the names of the columns using predefined method
df_new.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species',
       'sepal_area'],
      dtype='object')

In [31]:
# From the above output copy all the names except petal_length and store it in a list
names = ['sepal_length', 'sepal_width', 'petal_width', 'species','sepal_area']

In [32]:
# From the above list create a new dataframe "df_new2" from df_new which have only the columns mentioned in the list
# Print out the shape
df_new2 = df_new[names]
print(df_new2.shape)


(100, 5)


In [33]:
# Swap setosa with 1
# Swap virginica with 0
# Do this using replace()

df_new2['species'] = df_new2['species'].replace({'setosa' : 1,'virginica' : 0})
print(df_new2)

    sepal_length  sepal_width  petal_width  species  sepal_area
0            5.1          3.5          0.2        1       17.85
1            4.9          3.0          0.2        1       14.70
2            4.7          3.2          0.2        1       15.04
3            4.6          3.1          0.2        1       14.26
4            5.0          3.6          0.2        1       18.00
..           ...          ...          ...      ...         ...
95           6.7          3.0          2.3        0       17.10
96           6.3          2.5          1.9        0       16.53
97           6.5          3.0          2.0        0       17.98
98           6.2          3.4          2.3        0       12.75
99           5.9          3.0          1.8        0       15.96

[100 rows x 5 columns]


/var/folders/qd/k_nxlhp161gdwfh2kvvsftl80000gn/T/ipykernel_6591/4036480353.py:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_new2['species'] = df_new2['species'].replace({'setosa' : 1,'virginica' : 0})
/var/folders/qd/k_nxlhp161gdwfh2kvvsftl80000gn/T/ipykernel_6591/4036480353.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_new2['species'] = df_new2['species'].replace({'setosa' : 1,'virginica' : 0})


**Assignment END<br>
Please submit this on teams before the deadline**