In [14]:
#Question1

x = int(input("x: "))
y = float(input("y: "))
z = input("z: ")
print(type(x), type(y), type(z))
a = x**2
b = y**2
print("square of x", a)
print("square of y", b)
a = (a + 97 -3)/x
b = (b + 97 - 3)/y
print("Final x:", a)
print("Final y:", b)
z = z + "Sumit"
print("Final z:", z)

x: 34
y: 56
z: abghicfusrtee
<class 'int'> <class 'float'> <class 'str'>
square of x 1156
square of y 3136.0
Final x: 36.76470588235294
Final y: 57.67857142857143
Final z: abghicfusrteeSumit


In [13]:
#Question2

def multi_table():
    x = int(input("Enter a number: "))
    i = 1
    while i < 21 :
        print(f"{x}*{i}:", x*i)
        i = i + 1

multi_table()


Enter a number: 67
67*1: 67
67*2: 134
67*3: 201
67*4: 268
67*5: 335
67*6: 402
67*7: 469
67*8: 536
67*9: 603
67*10: 670
67*11: 737
67*12: 804
67*13: 871
67*14: 938
67*15: 1005
67*16: 1072
67*17: 1139
67*18: 1206
67*19: 1273
67*20: 1340


In [15]:
#Question 3

count = 0
for some in z:
    if(some == "a" or some == "e" or some == "i" or some == "o" or some == "u"):
        count += 1
print("No. of vowels in Final z:", count)

No. of vowels in Final z: 7


In [16]:
#Question 4
import numpy as np

In [17]:
#Create numpy array of size 10
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
#resize array
a = a.reshape((10, 1))
print(a.shape)

(10, 1)


In [25]:
#array of all element 1
b = np.ones((10,1))
#add a+b
c = a+b

array([[ 2.],
       [ 3.],
       [ 4.],
       [ 5.],
       [ 6.],
       [ 7.],
       [ 8.],
       [ 9.],
       [10.],
       [11.]])

In [28]:
#5 rows of new vector
print(c[0:5])

[[2.]
 [3.]
 [4.]
 [5.]
 [6.]]


In [29]:
#random values
d = np.random.rand(10, 1)
d

array([[0.90261388],
       [0.90800225],
       [0.94896085],
       [0.483488  ],
       [0.83293048],
       [0.67872572],
       [0.20260046],
       [0.85067605],
       [0.75141689],
       [0.92190598]])

In [31]:
#hstack()
x = np.hstack([c, d])
#print(x)
y = np.vstack([c, d])
#print(y)
print("shape of hstack vector:", x.shape)
print("shape of vstack vector:", y.shape)
#difference
# hstack adds horizontally, vstack veritically

shape of hstack vector: (10, 2)
shape of vstack vector: (20, 1)


In [32]:
#list
list1 = [1, 2, 3, 4, 4, 5, 6]
a = np.array(list1)
print(a**2)

[ 1  4  9 16 16 25 36]


In [95]:
#Question 4
#Broadcasting
"""
Broadcasting is a mechanism for communication where sender send data to all nodes present in a network.
We don't have choice, we have to receive the data.
Example, Radio-- In radio broadcasting audio content is distributed via radio waves.
"""

"\nBroadcasting is a mechanism for communication where sender send data to all nodes present in a network.\nWe don't have choice, we have to receive the data.\nExample, Radio-- In radio broadcasting audio content is distributed via radio waves.\n"

In [34]:
#Question 5
import pandas as pd

In [40]:
#file path
path = pd.read_csv("/home/sumit/basic_py/iris.csv")
path

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [43]:
#first seven rows
print(path.head(7))

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa
5           5.4          3.9           1.7          0.4  setosa
6           4.6          3.4           1.4          0.3  setosa


In [46]:
#last 10 rows
path.tail(10) #we can use print or not

sepal_length  sepal_width  petal_length  petal_width    species
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [45]:
#no. of rows and column
path.shape

(150, 5)

In [49]:
#info
path.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [52]:
#check null values
path.isnull().values.any()

False

In [54]:
#standard dimension
path["petal_width"].std()

0.7631607417008414

In [62]:
#name of columns
path.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [60]:
#species column
path["species"].nunique()

3

In [64]:
#rows with column value setosa
path[path["species"] == "setosa"].shape

(50, 5)

In [66]:
#rows with column value virginica
path[path["species"] == "virginica"].shape

(50, 5)

In [69]:
#df_new by concatenating
df_new = pd.concat([path[path["species"] == "setosa"], path[path["species"] == "virginica"]])
df_new.shape

(100, 5)

In [70]:
#average of sepal length
df_new["sepal_length"].mean()

5.797

In [73]:
#sepal_area
df_new["sepal_area"] = df_new["sepal_length"]*df_new["sepal_width"]
print("max area:", df_new["sepal_area"].max())
print("min area:", df_new["sepal_area"].min())

max area: 30.02
min area: 10.35


In [76]:
#name of columns
df_new.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species',
       'sepal_area'],
      dtype='object')

In [83]:
#list
list2 = df_new.drop("petal_length", axis = 1).columns
list2

Index(['sepal_length', 'sepal_width', 'petal_width', 'species', 'sepal_area'], dtype='object')

In [86]:
#df_new2
df_new2 = df_new.drop("petal_length", axis = 1)
df_new2.shape

(100, 5)

In [93]:
#replace()
df_new2.replace("setosa", "1", inplace = True)
df_new2.replace("virginica", "0", inplace = True)
df_new2

sepal_length  sepal_width  petal_width species  sepal_area
0             5.1          3.5          0.2       1       17.85
1             4.9          3.0          0.2       1       14.70
2             4.7          3.2          0.2       1       15.04
3             4.6          3.1          0.2       1       14.26
4             5.0          3.6          0.2       1       18.00
..            ...          ...          ...     ...         ...
145           6.7          3.0          2.3       0       20.10
146           6.3          2.5          1.9       0       15.75
147           6.5          3.0          2.0       0       19.50
148           6.2          3.4          2.3       0       21.08
149           5.9          3.0          1.8       0       17.70

[100 rows x 5 columns]